### PR TITLE
Add mc priority and remove dmc virtual

### PR DESCRIPTION
**Pull request by 5im1z**
Since the prioritization is getting complex... I'm doing a weighted score-assignment logic when selecting a profile. Please let me know if this makes sense and if I'm not explaining anything adequately in the comments!!

### CODE REVIEW

**Comment by 5im1z** [comment]
For more detailed motivation of this task: https://app.asana.com/0/1207650697591573/1208146775629519/f

**Review by dpmccabe — APPROVED** [review]
I don't have a working version of this repo anymore and it's not really installable since a working set of dependencies aren't tracked anywhere, so I wasn't able to walk through this code. Looks reasonable though.

**Comment by gulatide** [comment]
On L289-293, why are we considering model conditions that have NA for the drug condition as part of the non-drugged MC table?

**Comment by 5im1z** [comment]
> On L289-293, why are we considering model conditions that have NA for the drug condition as part of the non-drugged MC table?

When the drug field is empty that means the MC has not been drugged

**Comment by gulatide** [comment]
It would be helpful to add the additional info on Asana as comments in the code (e.g. None > DMSO > drug)

**Comment by gulatide** [comment]
On L319, I might be missing something but don't see how this code would work since the 'source' column in Gumbo is of type string?

subset_seq_table.loc[subset_seq_table.Drug == "DMSO", "source"] += 100

**Comment by 5im1z** [comment]
> On L319, I might be missing something but don't see how this code would work since the 'source' column in Gumbo is of type string?
> 
> subset_seq_table.loc[subset_seq_table.Drug == "DMSO", "source"] += 100

The previous line `subset_seq_table["source"].map(source_priority)` maps strings to numbers

**Review by gulatide — APPROVED** [review]

**Pull request merged**
